refactor(http): Using HttpStatus.valueOf method to populate HttpStatus object.
In Spring framework 6, HttpStatusCode has been introduced which is implemented by HttpStatus.

```
> Task :orca-webhook:compileJava
orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.java:130: error: incompatible types: HttpStatusCode cannot be converted to HttpStatus
      if (shouldRetry(statusCode, stageData)) {
                      ^
orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.java:175: error: incompatible types: HttpStatusCode cannot be converted to HttpStatus
    monitor.setStatusCode(response.getStatusCode());
                                                ^
orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/WebhookResponseProcessor.java:85: error: incompatible types: HttpStatusCode cannot be converted to HttpStatus
    webhookOutput.setStatusCode(e.getStatusCode());
                                               ^
orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/WebhookResponseProcessor.java:93: error: incompatible types: HttpStatusCode cannot be converted to HttpStatus
    TaskResult result = processReceivedFailureStatusCode(e.getStatusCode(), webhookOutput);
                                                                        ^
orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/WebhookResponseProcessor.java:165: error: incompatible types: HttpStatusCode cannot be converted to HttpStatus
    webhookOutput.setStatusCode(response.getStatusCode());
                                                      ^
orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/WebhookResponseProcessor.java:174: error: incompatible types: HttpStatusCode cannot be converted to HttpStatus
    HttpStatus status = response.getStatusCode();
```

Reference:
https://github.com/spring-projects/spring-framework/issues/28214