refactor(security): Including csrf token with mock mvc request when testing any non-safe HTTP methods.
```
AdminControllerTest > minutests() > com.netflix.spinnaker.orca.controllers.AdminControllerTest.minutests()[1] FAILED
    ▼ Expect that 403:
      ✗ is equal to 200
              found 403
        at app//com.netflix.spinnaker.orca.controllers.AdminControllerTest$tests$1$2.invoke(AdminControllerTest.kt:60)
        at app//com.netflix.spinnaker.orca.controllers.AdminControllerTest$tests$1$2.invoke(AdminControllerTest.kt:42)

KubernetesPreconfiguredJobSpec > minutests() > kubernetes preconfigured job > com.netflix.spinnaker.orca.clouddriver.pipeline.KubernetesPreconfiguredJobSpec.minutests()[1][2] FAILED
    ▼ Expect that 403:
      ✗ is equal to 200
              found 403

LambdaTrafficRoutingStageTest > LambdaTrafficRoutingStageIntegrationTest() FAILED
    org.opentest4j.AssertionFailedError: expected: <403> but was: <200>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
        at app//com.netflix.spinnaker.orca.clouddriver.pipeline.providers.aws.lambda.LambdaTrafficRoutingStageTest.LambdaTrafficRoutingStageIntegrationTest(LambdaTrafficRoutingStageTest.java:89)
```

Reference:
https://docs.spring.io/spring-security/reference/servlet/test/mockmvc/csrf.html